name: Crypto Liquidity Bot

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Execution mode"
        required: false
        default: "manual"
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_RUN_MODE: ${{ inputs.run_mode }}
        run: python bot.py
